spring.application.name=ytrep
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/Yourep}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345678}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minio}
minio.secret-key=${MINIO_SECRET_KEY:minio123}
minio.video=videos
minio.thumbnail=thumbnails
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000
app.jwt.secret=${JWT_SECRET:MySecretKeyMustbeAtleast256BitsLongFor256Algorithm}
app.jwt.expiration=${JWT_EXPIRATION_MS:86400000}

server.tomcat.threads.max=50
server.tomcat.connection-timeout=5000
spring.mvc.async.request-timeout=30000

logging.level.org.springframework.security = DEBUG
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always